
language: node_js

node_js:
  - '6'

before_script:
  - chmod -R +x sh

deploy:
  provider: script
  script: sh/deploy.sh
  on:
    tags: true

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm # For RPM (Fedora)
      - bsdtar # For pacman (Arch Linux)
