
language: node_js

os:
  - linux
  - osx

dist: trusty

sudo: required

node_js:
  - '6'

before_script:
  - chmod -R +x sh

before_deploy:
  - export CSC_IDENTITY_AUTO_DISCOVERY=false
  - bash travis/$(node -p 'process.platform').addons/main.sh
  - npm run pack
  - ls dist/{,linux,mac} || true

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file:
    - dist/*.pacman
    - dist/*.deb
    - dist/*.rpm
    - dist/*.AppImage
    - dist/*.exe
    - dist/*.zip
    - dist/*.7z
    - dist/linux/*.pacman
    - dist/linux/*.deb
    - dist/linux/*.rpm
    - dist/linux/*.AppImage
    - dist/mac/*.zip
    - dist/mac/*.7z
    - dist/win/*.exe
    - dist/win/*.zip
    - dist/win/*.7z
  on:
    tags: true
