
language: node_js

node_js:
  - '6'

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_deploy:
        - bash travis/linux.addons/main.sh
        - OPTIONS="linux $OPTIONS" npm run pack
        - ls dist/{,linux,mac} || true
    - os: osx
      sudo: required
      before_deploy:
        - bash travis/mac.addons/main.sh
        - OPTIONS="mac $OPTIONS" npm run pack
        - ls dist/{,linux,mac} || true

before_script:
  - chmod -R +x sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file:
    - dist/*.pacman
    - dist/*.deb
    - dist/*.rpm
    - dist/*.AppImage
    - dist/*.exe
    - dist/*.zip
    - dist/*.7z
    - dist/linux/*.pacman
    - dist/linux/*.deb
    - dist/linux/*.rpm
    - dist/linux/*.AppImage
    - dist/mac/*.zip
    - dist/mac/*.7z
    - dist/win/*.exe
    - dist/win/*.zip
    - dist/win/*.7z
  on:
    tags: true
