
language: node_js

dist: trusty

sudo: required

node_js:
  - '6'

env:
  - BEFORE_DEPLOY_SCRIPT='bash sh/ci/pack.sh'

jobs:
  include:
    - stage: before_script
      script: TARGET_OS=linux TARGET_ARCH=ia32 exec $BEFORE_DEPLOY_SCRIPT
    - stage: before_script
      script: TARGET_OS=linux TARGET_ARCH=x64 exec $BEFORE_DEPLOY_SCRIPT
    - stage: before_script
      script: TARGET_OS=linux TARGET_ARCH=armv7l exec $BEFORE_DEPLOY_SCRIPT
    - stage: before_script
      script: TARGET_OS=mac exec $BEFORE_DEPLOY_SCRIPT

before_script:
  - chmod -R +x sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file:
    - dist/*.*
    - dist/linux/*.*
    - dist/mac/*.7z
    - dist/mac/*.zip
    - dist/win/*.*
  on:
    tags: true
