
language: node_js

dist: xenial

sudo: required

node_js:
  - '6'

before_script:
  - chmod -R +x sh

before_deploy:
  - bash addons/main.sh
  - OPTIONS="linux mac win $OPTIONS" npm run pack
  - ls dist/{,mac,win} || true

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file:
    - dist/*.pacman
    - dist/*.deb
    - dist/*.rpm
    - dist/*.AppImage
    - dist/*.zip
    - dist/*.7z
    - dist/mac/*.zip
    - dist/mac/*.7z
    - dist/win/*.exe
    - dist/win/*.zip
    - dist/win/*.7z
  on:
    tags: true
