
language: node_js

node_js:
  - '6'

before_script:
  - chmod -R +x sh

before_deploy:
  - OPTIONS="linux mac $OPTIONS" npm run pack

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_OAUTH
  skip_cleanup: true
  file_glob: true
  file:
    - dist/*.pacman
    - dist/*.deb
    - dist/*.rpm
    - dist/*.AppImage
    - dist/*.7z
    - dist/mac/*.7z
  on:
    tags: true

addons:
  apt:
    packages:
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm # For RPM (Fedora)
      - bsdtar # For pacman (Arch Linux)
