branches:
  except:
    - gh-pages

environment:
  ALTER_NPM: yarn
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7

cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%APPDATA%\npm'
  - '%APPDATA%\npm-cache'
  - '%APPDATA%\yarn'
  - '%APPDATA%\yarn-cache'
  - node_modules

image: Visual Studio 2015

clone_folder: C:\Projects\Main

clone_depth: 1

install:
  - cmd: echo "Repo URL" && git remote get-url origin
  - ps: powershell sh/ci/appveyor/install.ps1
  - cmd: yarn install

test_script:
  - cmd: echo "NodeJS version" && node --version
  - cmd: echo "Yarn version" && yarn --version
  - cmd: echo "Test" && yarn test

build_script:
  - cmd: yarn run pack
